# Generated by Django 5.2.7 on 2025-10-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
